server:
  port: 8088

spring:
  aop:
    auto: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #        url: jdbc:mysql://localhost:3306/travel
    #        username: root
    #        password: 123456

    druid:
      filters: stat,wall
      aop-patterns: com.lhnfinal.travel.*
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/travel?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=CTT
      username: root
      password: 123456

      filter:
        wall:
          enabled: true
          config:
            comment-allow: true
        stat:
          enabled: true

      web-stat-filter:
        enabled: true
        url-pattern: /*

      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
